#!/usr/bin/perl -w
#<Oramx converts oracle to sqlmx.>
#Copyright (C) <2014> <Janith Perera>

#------------------------------------------------------------------------------
# Name     : Oramx/oramx.pl
# Language : Perl
# Authors  : Janith Perera, janith@member.fsf.org
# Function : Main program
# Usage    : See documentation
#------------------------------------------------------------------------------
#
#          This file is part of Oramx.
#
#          Oramx is free software: you can redistribute it and/or modify
#          it under the terms of the GNU General Public License as published by
#          the Free Software Foundation, either version 3 of the License, or
#          (at your option) any later version.
#
#          Oramx is distributed in the hope that it will be useful,
#          but WITHOUT ANY WARRANTY; without even the implied warranty of
#          MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#          GNU General Public License for more details.
#
#          You should have received a copy of the GNU General Public License
#          along with Oramx. If not, see <http://www.gnu.org/licenses/>.
#
#------------------------------------------------------------------------------

use lib '.';
use warnings;
use strict;
use Oramx;
use Getopt::Long;

my $conf = 'oramx.conf';
my $file = undef;
my $help = undef;

GetOptions('c|config=s' => \$conf,
           'f|file=s' => \$file,
	   'h|help' => \$help
    );


sub usage
{
    print qq{                                                                                                                                            
Usage: oramx [--option value]
    
   -c | --config  : configuration file name.
                                                                                                 
   -f | --file  : Output file (the result will be written here).

   -h | --help

};
    exit 0;
}

if ($help){
    usage();
}

my $oramx_obj = Oramx::new("Oramx",
    "config", $conf,
    "query_file", $file );
$oramx_obj->main();


exit(0);
